version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: restaurant_manager
      POSTGRES_PASSWORD: restauranto
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    restart: always

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_restaurant
      POSTGRES_USER: test_restaurant_manager
      POSTGRES_PASSWORD: test_restauranto
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
      - ./database/test_scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db-data:
  test-db-data:
